CREATE TABLE `applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicantId` int NOT NULL,
	`irbNumber` varchar(64),
	`status` enum('draft','stage1_pending','stage1_failed','stage2_pending','stage2_failed','submitted','under_review','pending_admin','approved','rejected','resubmission_required','permanently_rejected') NOT NULL DEFAULT 'draft',
	`submissionCount` int NOT NULL DEFAULT 1,
	`researchType` enum('clinical_trial','observational','retrospective','survey_questionnaire','case_study','laboratory','educational','social_behavioral','other'),
	`irbCategory` enum('full_board','expedited','exempt'),
	`researchTitle` text,
	`principalInvestigator` varchar(255),
	`piEmail` varchar(320),
	`piInstitution` varchar(255),
	`piDepartment` varchar(255),
	`fundingSource` varchar(255),
	`estimatedDuration` varchar(128),
	`stage1AiScore` int,
	`stage1AiFeedback` text,
	`stage1Passed` boolean,
	`researchObjectives` text,
	`methodology` text,
	`sampleSize` varchar(128),
	`targetPopulation` text,
	`inclusionCriteria` text,
	`exclusionCriteria` text,
	`dataCollectionMethods` text,
	`informedConsentProcess` text,
	`riskAssessment` text,
	`benefitAssessment` text,
	`confidentialityMeasures` text,
	`conflictOfInterest` text,
	`previousIrbApproval` text,
	`additionalDocumentsUrl` text,
	`rejectionFileUrl` text,
	`stage2AiScore` int,
	`stage2AiFeedback` text,
	`stage2Passed` boolean,
	`adminNotes` text,
	`rejectionReason` text,
	`certificateUrl` text,
	`approvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`submittedAt` timestamp,
	CONSTRAINT `applications_id` PRIMARY KEY(`id`),
	CONSTRAINT `applications_irbNumber_unique` UNIQUE(`irbNumber`)
);
--> statement-breakpoint
CREATE TABLE `audit_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int,
	`userId` int,
	`action` varchar(128) NOT NULL,
	`details` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `audit_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `committee_members` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`specialization` varchar(255),
	`title` varchar(128),
	`institution` varchar(255),
	`isActive` boolean NOT NULL DEFAULT true,
	`totalAssignments` int NOT NULL DEFAULT 0,
	`totalResponses` int NOT NULL DEFAULT 0,
	`totalApprovals` int NOT NULL DEFAULT 0,
	`totalRejections` int NOT NULL DEFAULT 0,
	`averageResponseTimeMs` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `committee_members_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `review_assignments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int NOT NULL,
	`committeeMemberId` int NOT NULL,
	`assignedBy` enum('system','admin') NOT NULL DEFAULT 'system',
	`status` enum('pending','approved','rejected','expired') NOT NULL DEFAULT 'pending',
	`comments` text,
	`assignedAt` timestamp NOT NULL DEFAULT (now()),
	`respondedAt` timestamp,
	`expiresAt` timestamp NOT NULL,
	CONSTRAINT `review_assignments_id` PRIMARY KEY(`id`)
);
