/** Public FAQs are loaded by information pages, separately from global route metadata. */
export const PLATFORM_FAQS = [
  { qEn: "What does this platform do?", qAr: "ما الذي تقدمه المنصة؟", aEn: "It helps researchers prepare and track research ethics applications, organize documents, and work with authorized human reviewers. AI supports preparation and assessment; an AI score is not ethics approval.", aAr: "تساعد الباحثين على إعداد طلبات أخلاقيات البحث ومتابعتها وتنظيم المستندات والعمل مع مراجعين بشريين مخولين. يدعم الذكاء الاصطناعي الإعداد والتقييم، ولا تُعد درجته موافقة أخلاقية." },
  { qEn: "How long does review take?", qAr: "كم تستغرق المراجعة؟", aEn: "Screening starts the moment you submit, reviewers are assigned with a 24-hour review window, and the service target is a first review within 24 hours for complete applications. Higher-risk studies, full-board review or questions to the applicant can take longer; the target is not a guarantee of an outcome.", aAr: "يبدأ الفحص فور التقديم، ويُكلَّف المراجعون بمهلة مراجعة 24 ساعة، وهدف الخدمة إتمام المراجعة الأولى خلال 24 ساعة للطلبات المكتملة. قد تستغرق الدراسات الأعلى خطورة أو المراجعة الكاملة أو الاستفسارات الموجهة للباحث وقتاً أطول، والهدف ليس ضماناً لنتيجة معينة." },
  { qEn: "How can I get a faster decision?", qAr: "كيف أحصل على قرار أسرع؟", aEn: "Submit a complete application: a clear primary objective, a justified sample size, a complete consent process (or a justified waiver), safeguards for vulnerable groups, a data protection plan and risks with mitigation. The submit page shows instant quality tips for each of these before you send.", aAr: "قدّم طلباً مكتملاً: هدف رئيس واضح، وحجم عينة مبرر، وعملية موافقة مكتملة (أو إعفاء مبرر)، وضمانات للفئات المستضعفة، وخطة لحماية البيانات، ومخاطر مع إجراءات تخفيفها. تعرض صفحة التقديم نصائح جودة فورية لكل منها قبل الإرسال." },
  { qEn: "Does AI decide whether my research is approved?", qAr: "هل يقرر الذكاء الاصطناعي الموافقة على بحثي؟", aEn: "No. AI helps you prepare and helps reviewers work faster, but every ethics decision is made and recorded by qualified, authorized people.", aAr: "لا. يساعدك الذكاء الاصطناعي في الإعداد ويساعد المراجعين على العمل بسرعة أكبر، لكن كل قرار أخلاقي يتخذه ويسجله أشخاص مؤهلون ومخولون." },
  { qEn: "Can I apply by chat instead of a long form?", qAr: "هل يمكنني التقديم عبر المحادثة بدلاً من نموذج طويل؟", aEn: "Yes. The chat application asks one question at a time in Arabic or English and fills the same protocol sections for you to review and edit before submitting.", aAr: "نعم. يطرح التقديم بالمحادثة سؤالاً واحداً في كل مرة بالعربية أو الإنجليزية ويملأ أقسام البروتوكول نفسها لتراجعها وتعدلها قبل التقديم." },
  { qEn: "Which rules is the platform aligned with?", qAr: "ما الأنظمة التي تتوافق معها المنصة؟", aEn: "Guidance and checks follow the Saudi Law of Ethics of Research on Living Creatures and its Implementing Regulations (NCBE), the Personal Data Protection Law, and international guidance such as the Declaration of Helsinki, ICH Good Clinical Practice and CIOMS. The platform does not claim government affiliation or accreditation.", aAr: "تتبع الإرشادات والفحوص نظام أخلاقيات البحث على المخلوقات الحية ولائحته التنفيذية (اللجنة الوطنية للأخلاقيات الحيوية)، ونظام حماية البيانات الشخصية، والإرشادات الدولية مثل إعلان هلسنكي والممارسة السريرية الجيدة (ICH) ومجلس CIOMS. لا تدّعي المنصة تبعية حكومية أو اعتماداً رسمياً." },
  { qEn: "Can I upload participant or patient records?", qAr: "هل يمكنني رفع سجلات المشاركين أو المرضى؟", aEn: "Use protocol-level information and de-identified examples. Do not put patient identifiers, medical records, passwords, or API keys in chat or generated documents. Follow your institution's approved data handling rules.", aAr: "استخدم معلومات البروتوكول وأمثلة منزوعة الهوية. لا تُدخل معرّفات المرضى أو سجلاتهم الطبية أو كلمات المرور أو مفاتيح API في المحادثة أو المستندات المنشأة. اتبع قواعد التعامل مع البيانات المعتمدة لدى مؤسستك." },
  { qEn: "Does verification mean a certificate is accepted worldwide?", qAr: "هل يعني التحقق أن الشهادة مقبولة عالمياً؟", aEn: "No. Verification confirms a record held by this platform. Acceptance depends on the issuing committee's authority and the receiving institution and jurisdiction. Expansion from 2027 is a roadmap, not automatic global regulatory validity.", aAr: "لا. يؤكد التحقق وجود سجل لدى المنصة. ويعتمد قبوله على صلاحية اللجنة المصدرة ومتطلبات المؤسسة المستقبلة والدولة المعنية. التوسع ابتداءً من 2027 خطة مستقبلية، ولا يمنح صلاحية تنظيمية عالمية تلقائية." },
  { qEn: "How do I verify an IRB record?", qAr: "كيف أتحقق من سجل IRB؟", aEn: "Open Verify IRB and enter the reference number. Check the current status and dates, including any retraction, before relying on an issued record.", aAr: "افتح صفحة التحقق من IRB وأدخل الرقم المرجعي. تحقق من الحالة الحالية والتواريخ وأي سحب للموافقة قبل الاعتماد على السجل." },
] as const;
